repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.1
    hooks:
      - id: golangci-lint
        args: ["run"]

  - repo: https://github.com/go-modules/validate
    rev: v0.2.2
    hooks:
      - id: go-mod-tidy

  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: go
        args: ["test", "./..."]
        language: go
        types: [go]
